apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensor.fullname" . | quote }}
  labels:
    {{- include "sensor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sensor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | quote | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sensor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name | quote }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/etc/brave/ssl"
            name: sensors-tls
            readOnly: true
        env:
          - name: TWILIO_SID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: TWILIO_SID
          - name: TWILIO_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: TWILIO_TOKEN
          - name: TWILIO_MESSAGING_SERVICE_SID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: TWILIO_MESSAGING_SERVICE_SID
          - name: WEB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: WEB_USERNAME
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PASSWORD
          - name: REDIS_CLUSTER_IP
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: REDIS_CLUSTER_IP
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: SECRET
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PG_USER
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PG_DATABASE
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PG_PORT
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PG_HOST
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PG_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: SENTRY_DSN
          - name: RADAR_THRESHOLD_SECONDS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: RADAR_THRESHOLD_SECONDS
          - name: DOOR_THRESHOLD_SECONDS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: DOOR_THRESHOLD_SECONDS
          - name: SESSION_RESET_THRESHOLD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: SESSION_RESET_THRESHOLD
          - name: SUBSEQUENT_ALERT_MESSAGE_THRESHOLD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: SUBSEQUENT_ALERT_MESSAGE_THRESHOLD
          - name: RADAR_WINDOW_SIZE_SECONDS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: RADAR_WINDOW_SIZE_SECONDS
          - name: PARTICLE_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PARTICLE_ACCESS_TOKEN
          - name: PARTICLE_PRODUCT_GROUP
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PARTICLE_PRODUCT_GROUP
          - name: ONESIGNAL_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: ONESIGNAL_APP_ID
          - name: ONESIGNAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: ONESIGNAL_API_KEY
          - name: LOW_BATTERY_ALERT_TIMEOUT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: LOW_BATTERY_ALERT_TIMEOUT
          - name: ONESIGNAL_ALERT_ANDROID_CATEGORY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: ONESIGNAL_ALERT_ANDROID_CATEGORY_ID
          - name: SUBSEQUENT_VITALS_ALERT_THRESHOLD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: SUBSEQUENT_VITALS_ALERT_THRESHOLD
          - name: CLICKUP_TEAM_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: CLICKUP_TEAM_NAME
          - name: CLICKUP_TEAM_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: CLICKUP_TEAM_ID
          - name: MAX_STILLNESS_ALERTS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: MAX_STILLNESS_ALERTS
          - name: PA_API_KEY_PRIMARY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PA_API_KEY_PRIMARY
          - name: PA_API_KEY_SECONDARY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PA_API_KEY_SECONDARY
          - name: PA_PASSWORD_PRIMARY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PA_PASSWORD_PRIMARY
          - name: PA_PASSWORD_SECONDARY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PA_PASSWORD_SECONDARY
          - name: PARTICLE_WEBHOOK_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: PARTICLE_WEBHOOK_API_KEY
          - name: IS_DB_LOGGING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: IS_DB_LOGGING
          - name: DOMAIN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName | quote }}
                key: DOMAIN
          - name: ENVIRONMENT
            value: {{ include "sensor.fullname" . | quote }}
          - name: RELEASE
            value: {{ .Values.image.tag | quote }}
      volumes:
        - name: sensors-tls
          secret:
            secretName: sensors-tls
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
